apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: asgard-gateway
  labels:
    app: asgard-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: asgard-gateway
  template:
    metadata:
      labels:
        app: asgard-gateway
    spec:
      containers:
        - name: asgard-gateway
          image: registry.digitalocean.com/francisco/asgard-gateway:202305131923
          resources: {}
          ports:
            - containerPort: 8080
