name: CI

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  REPO_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches:
      - env.BRANCH_NAME
  pull_request:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: env.REPO_NAME
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.17'
        cache: false
    - name: Install RPC
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        repository: sugarshop/rpc
        path: rpc
    - name: Install dependencies
      working-directory: env.REPO_NAME
      run: |
        go mod download
        go install github.com/cloudwego/kitex/tool/cmd/kitex@v0.1.3
        go install github.com/cloudwego/thriftgo@v0.2.9
        sh kitex.sh
    - name: Lint Check
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
        working-directory: env.REPO_NAME
      env:
        GO111MODULE: "on"
    - name: Run unit tests
      working-directory: env.REPO_NAME
      run: |
        go test -v ./...
  ut:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: env.REPO_NAME
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.17'
        cache: false
    - name: Install RPC
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        repository: sugarshop/rpc
        path: rpc
    - name: Install dependencies
      working-directory: env.REPO_NAME
      run: |
        go mod download
        go install github.com/cloudwego/kitex/tool/cmd/kitex@v0.1.3
        go install github.com/cloudwego/thriftgo@v0.2.9
        sh kitex.sh
    - name: Run unit tests
      working-directory: env.REPO_NAME
      run: |
        go test -v ./...